development:
  adapter: mysql
  encoding: utf8
  database: rails_game
  user: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  encoding: utf8
  database: rails_game_test
  user: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: rails_game
  user: root
  pool: 5
  timeout: 5000
